# File: glances-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: glances
spec:
  selector:
    app: glances
  ports:
    - protocol: TCP
      port: 80
      targetPort: 61208
